import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // next-env.d.ts is regenerated by `next build`/`next dev` and is marked
    // "should not be edited" by Next.js itself — it's gitignored and not
    // ours to fix lint findings in.
    // `.next-stale-*` are abandoned build directories kept around after a
    // locked-directory failure. They are generated output, not source, and
    // linting them reported 45 phantom errors in Next.js's own emitted code.
    ignores: [
      'out/**',
      '.next/**',
      '.next-stale-*/**',
      'graphify-out/**',
      'node_modules/**',
      'next-env.d.ts',
    ],
  },
];

export default eslintConfig;
