import { dirname } from 'path';
import { fileURLToPath } from 'url';
import { FlatCompat } from '@eslint/eslintrc';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    // next-env.d.ts is regenerated by `next build`/`next dev` and is marked
    // "should not be edited" by Next.js itself — it's gitignored and not
    // ours to fix lint findings in.
    ignores: ['out/**', '.next/**', 'node_modules/**', 'next-env.d.ts'],
  },
];

export default eslintConfig;
